[versions]

# ПЛАГИНЫ
plugin_agp = "8.11.2"
plugin_compose = "1.9.3"
kotlin = "2.2.20"

# БИБЛИОТЕКИ
android-compileSdk = "36"
android-minSdk = "24"
android-targetSdk = "36"
androidx-activityCompose = "1.11.0"
junit = "4.13.2"
compose = "1.9.3"
kotlinStdlib = "2.2.20"
runner = "1.5.2"
core = "1.5.0"
androidxRoom = "2.8.3"
sqlite = "2.6.1"
kotlin_coroutines_core_version = "1.10.2"
compottieVersion = "2.0.2"
nav_version = "2.9.1"
kodein_version = "7.28.0"

[libraries]

# jetbrains kotlin
kotlin-coroutines-core = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-core", version.ref = "kotlin_coroutines_core_version" }

# room
androidx-room-compiler = { group = "androidx.room", name = "room-compiler", version.ref = "androidxRoom" }
androidx-room-runtime = { group = "androidx.room", name = "room-runtime", version.ref = "androidxRoom" }
sqlite-bundled = { module = "androidx.sqlite:sqlite-bundled", version.ref = "sqlite" }
sqlite = { module = "androidx.sqlite:sqlite", version.ref = "sqlite" }

# compose
androidx-activity-compose = { module = "androidx.activity:activity-compose", version.ref = "androidx-activityCompose" }
compose-ui-tooling = { module = "androidx.compose.ui:ui-tooling", version.ref = "compose" }
compose-ui-tooling-preview = { module = "androidx.compose.ui:ui-tooling-preview", version.ref = "compose" }

# навигация compose
compose-navigation = { module = "org.jetbrains.androidx.navigation:navigation-compose", version.ref = "nav_version" }

# потом почистить (удалить лишние)
kotlin-test = { module = "org.jetbrains.kotlin:kotlin-test", version.ref = "kotlin" }
kotlin-testJunit = { module = "org.jetbrains.kotlin:kotlin-test-junit", version.ref = "kotlin" }
junit = { module = "junit:junit", version.ref = "junit" }
kotlin-stdlib = { group = "org.jetbrains.kotlin", name = "kotlin-stdlib", version.ref = "kotlinStdlib" }
androidx-runner = { group = "androidx.test", name = "runner", version.ref = "runner" }
androidx-core = { group = "androidx.test", name = "core", version.ref = "core" }

# анимации из JSON
compottie = { module = "io.github.alexzhirkevich:compottie", version.ref = "compottieVersion" }
compottie-dot = { module = "io.github.alexzhirkevich:compottie-dot", version.ref = "compottieVersion" }
compottie-network = { module = "io.github.alexzhirkevich:compottie-network", version.ref = "compottieVersion" }
compottie-resources = { module = "io.github.alexzhirkevich:compottie-resources", version.ref = "compottieVersion" }

# DI зависимости
kodein = { group = "org.kodein.di", name = "kodein-di", version.ref = "kodein_version" }

[plugins]
androidApplication = { id = "com.android.application", version.ref = "plugin_agp" }
androidLibrary = { id = "com.android.library", version.ref = "plugin_agp" }
jetbrainsCompose = { id = "org.jetbrains.compose", version.ref = "plugin_compose" }
composeCompiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
kotlinMultiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
kotlinSerialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
androidKotlinMultiplatformLibrary = { id = "com.android.kotlin.multiplatform.library", version.ref = "plugin_agp" }
androidLint = { id = "com.android.lint", version.ref = "plugin_agp" }
room = { id = "androidx.room", version.ref = "androidxRoom" }